### ISSUE TITLE
ORM Functionality

### ISSUE THREAD

**Issue by dalezak** [jannishuebl/couchmotion#2]
What is the estimated timeline for implementing ORM example from the readme?

class Item < CouchDBObject
end

item = Item.new
item.name = 'MyFantasticName'
item.price = 1.34

id = item.save

item = Item.find_by(id)

**Comment by jannishuebl** [comment]
Sadly I cannot work on this project anymore, because I am not using the Gem anymore in one of my own Project.

So there is currently no timeline for that. But of cause you are free Implement this feature by your own.

**Comment by dalezak** [comment]
Thanks for letting me know Jannis.
